version: "3"
services:
  jekyll:
    image: deweycw/dewey-lab:latest
    build: .
    ports:
      - 8081:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
